Add eslint to node bindings
ethereum/c-kzg-4844 pull request #269
Opened 2023-03-30 05:04 UTC by matthewkeil

No code changes were included.

## Inclusions
- Add industry standard `eslint`
- Run format
- Add command to makefile

2023-03-30 07:58 UTC, dapplion commented
If you removed Typescript to keep the bindings less verbose in terms of tooling, adding eslint kind of completely reverses that idea right? 
- referencing https://github.com/ethereum/c-kzg-4844/pull/260

2023-03-30 12:52 UTC, matthewkeil commented
I was talking with @jtraglia and he asked about some linting in the `C` code so I put up #268 and asked if I should add eslint for the TS/JS.  I do not feel strongly about this inclusion and am ok with either merging or closing this.  What are your thoughts @asn-d6

2023-03-30 13:20 UTC, jtraglia requested changes
Nice, I like this. Sure, setting up eslint is complicated, but the code looks better IMO.

Just a couple of small nits in the comments.

2023-03-30 13:20 UTC, jtraglia commented on bindings/node.js/Makefile
> +	@yarn eslint --quiet --color --ext .ts lib/ test/
I'd like for this to use the `$(YARN)` command to hide extraneous outputs.
```suggestion
	@$(YARN) eslint --quiet --color --ext .ts lib/ test/
```

Without it, I get this, which I don't find all that useful:
```
yarn run v1.22.19
$ /Users/jtraglia/Projects/mattk/c-kzg-4844/bindings/node.js/node_modules/.bin/eslint --quiet --color --ext .ts lib/ test/
```

2023-03-30 13:47 UTC, jtraglia commented on bindings/node.js/package.json
> +    "eslint-plugin-prettier": "^3.3.1",
Thanks, that warning is gone now 👍

2023-03-30 15:07 UTC, matthewkeil commented
There are merge conflicts from the last merge and there will be another round when the #268 gets merged.  I will fix them all in one go after that one is good to go.

2023-03-31 05:21 UTC, dapplion approved these changes

2023-03-31 08:46 UTC, asn-d6 commented
Let's do it!

2023-03-31 08:46 UTC, merged