Improve ckzg native library search path + small improvements
ethereum/c-kzg-4844 pull request #372
Opened 2023-10-03 11:39 UTC by flcl42

- `dylib` is better extension on Macos for "dynamically linked shared library"
- We do not care about old arch "x86_64-v2-win" because we will have that runtime check
- Library search path should be based on Ckzg.Bindings.dll location, not on the current directory. So `AppContext.BaseDirectory` is used
- The library may be built with any SDK

2023-10-03 13:05 UTC, jtraglia requested changes
Looks good, just one suggestion. Also, worth mentioning that, as of yesterday, there are arm64 builders for macOS available on GitHub workflows. Could simplify the build process a little.

* https://github.blog/changelog/2023-10-02-github-actions-apple-silicon-m1-macos-runners-are-now-available-in-public-beta/

2023-10-03 13:05 UTC, jtraglia commented on bindings/csharp/README.md
> +- `clang` as a prefered buid tool for the native wrapper of ckzg. On Windows it's tested with clang from [Microsoft Visual Studio components](https://learn.microsoft.com/en-us/cpp/build/clang-support
```suggestion
- `clang` as a preferred build tool for the native wrapper of ckzg. On Windows, it's tested with clang from [Microsoft Visual Studio components](https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170);
```

2023-10-04 08:18 UTC, flcl42 commented
> Looks good, just one suggestion. Also, worth mentioning that, as of yesterday, there are arm64 builders for macOS available on GitHub workflows. Could simplify the build process a little.
> 
>     * https://github.blog/changelog/2023-10-02-github-actions-apple-silicon-m1-macos-runners-are-now-available-in-public-beta/

It's available for paid plans only looks like.

2023-10-04 12:02 UTC, jtraglia commented
> It's available for paid plans only looks like.

Ah sad. I didn't catch that detail in the announcement.

2023-10-04 12:03 UTC, jtraglia approved these changes
LGTM. Thanks!

2023-10-04 12:03 UTC, merged