Add documentation for various internal/external functions
ethereum/c-kzg-4844 pull request #79
Opened 2023-01-23 14:35 UTC by asn-d6

2023-01-23 14:50 UTC, xrchz commented
Amazing - thanks!

Failing tests need to be fixed - I think one of the renames wasn't complete.

2023-01-23 15:11 UTC, xrchz commented on src/c_kzg_4844.c
> + * @param[out] out Pointer to the KZGProof object to store the result in.
it's just a boolean

2023-01-23 15:22 UTC, asn-d6 commented on src/c_kzg_4844.c
> + * @param[out] out Pointer to the KZGProof object to store the result in.
ugh. fixed in bd67d53

2023-01-23 15:30 UTC, jtraglia commented
One nit, there aren't tabs between tag, name, description.
```
@param[in] x a value
```
vs
```
@param[in] x    a value
```

2023-01-23 15:32 UTC, xrchz commented
I hope you mean alignment with spaces and not literal tabs?

2023-01-23 15:35 UTC, jtraglia commented
Ah yes, that's what I mean.

2023-01-24 09:26 UTC, asn-d6 commented
My editor does not do this in-comment alignment and it's a tedious job to do this. Is there a linter one can use, or can your editor do it automatically?

2023-01-24 09:32 UTC, xrchz commented
I can do the alignment thing after we merge. Can you fix the conflicts though (probably just rebase over latest commit)?

2023-01-24 13:31 UTC, jtraglia requested changes
Overall looks good. Thanks for this! Just a few nits.

2023-01-24 13:31 UTC, jtraglia commented on src/c_kzg_4844.c
> + * @remark `out` is left untouched if n == 0
Missing punctuation. First sentence & the remark.

2023-01-24 13:31 UTC, jtraglia commented on src/c_kzg_4844.c
> + * Verify a KZG proof claiming that p(z) == y.
Do you want to wrap `p(z)==y` in backticks here?

2023-01-24 13:31 UTC, jtraglia commented on src/c_kzg_4844.c
> + * Computes aggregate KZG proof given for multiple blobs
Missing punctuation.

2023-01-24 13:31 UTC, jtraglia commented on src/c_kzg_4844.c
> + * Helper function: Verify KZG proof claiming that p(z) == y
Missing punctuation and maybe wrap `p(z)==y` with backticks.

2023-01-24 13:32 UTC, jtraglia commented on src/c_kzg_4844.c
> + * @remark `out` is left untouched if n == 0
Oh also, for consistency I think you should wrap `n==0` in backticks.

2023-01-24 13:57 UTC, jtraglia approved these changes
LGTM thanks!

2023-01-24 14:02 UTC, merged